<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/10/21 16:12:34

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=rdm',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
