<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/02/25 13:10:01

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=rdm',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
